class AuthException(Exception):
    def __init__(self):
        super()
